# Generated by Django 3.0.3 on 2020-06-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0008_auto_20200610_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文件名')),
                ('path', models.FilePathField()),
                ('file', models.FileField(upload_to='media/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.ContentsModel', verbose_name='所属文章')),
            ],
            options={
                'verbose_name': '附件管理',
                'verbose_name_plural': '附件管理',
                'db_table': 'marilyn_attachment',
                'ordering': ['-created'],
            },
        ),
    ]
