# Generated by Django 3.0.3 on 2020-06-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachmentmodel',
            options={'ordering': ['-created'], 'verbose_name': '附件', 'verbose_name_plural': '附件'},
        ),
        migrations.RemoveField(
            model_name='attachmentmodel',
            name='path',
        ),
        migrations.AlterField(
            model_name='attachmentmodel',
            name='file',
            field=models.FileField(upload_to='media/upload/%Y/%m/%d/'),
        ),
    ]
