# Generated by Django 3.0.3 on 2020-06-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_auto_20200610_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentmodel',
            name='title',
        ),
        migrations.AlterField(
            model_name='attachmentmodel',
            name='file',
            field=models.FileField(upload_to='upload/%Y/%m/%d/'),
        ),
    ]
