# Generated by Django 3.0.3 on 2020-06-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_auto_20200610_1105'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachmentmodel',
            table='marilyn_attachments',
        ),
    ]
