# Generated by Django 3.0.3 on 2020-06-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Marilyn', max_length=30, verbose_name='站点名称')),
                ('keywords', models.CharField(blank=True, max_length=50, null=True, verbose_name='关键字')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('siteUrl', models.TextField(blank=True, max_length=50, null=True, verbose_name='站点网址')),
                ('allowRegister', models.BooleanField(default=False, verbose_name='是否允许注册')),
                ('defaultAllowComment', models.BooleanField(default=True, verbose_name='是否允许评论')),
            ],
            options={
                'verbose_name': '站点管理',
                'verbose_name_plural': '站点管理',
                'db_table': 'marilyn_options',
            },
        ),
    ]
