# Generated by Django 3.0.3 on 2020-06-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetasModel',
            fields=[
                ('mid', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='分类主键')),
                ('name', models.CharField(max_length=10, verbose_name='分类名称')),
                ('type', models.CharField(choices=[('category', '文章分类'), ('tag', '标签分类')], default='category', max_length=20, verbose_name='分类类型')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('count', models.IntegerField(default=0, verbose_name='文章数量')),
                ('parent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='metas.MetasModel', verbose_name='上级分类')),
            ],
        ),
    ]
